#!/bin/bash
echo "🎯 HybridOS Ultimate - Démonstrations Automatiques"
echo "================================================="
echo ""
echo "Ces commandes vous donneront un aperçu complet:"
echo ""
echo "📁 SYSTÈME DE FICHIERS:"
echo "   ls"
echo "   cd home/user"
echo "   cat readme.txt"
echo "   edit demo.c"
echo ""
echo "🎮 JEUX ET GRAPHICS:"
echo "   snake"
echo "   pong" 
echo "   matrix"
echo "   graphics"
echo ""
echo "💻 DÉVELOPPEMENT:"
echo "   compile demo.c"
echo "   basic \"PRINT \\\"Hello World\\\"\""
echo ""
echo "🌐 RÉSEAU:"
echo "   ping google.com"
echo "   http"
echo ""
echo "🔧 SYSTÈME:"
echo "   ps"
echo "   help"
echo "   about"
echo ""
echo "🚀 Lancez HybridOS avec: ./run-ultimate.sh"
